name: water_intake
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.4+6

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.3
  intl: ^0.20.2
  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.9.0
  shared_preferences: ^2.5.5
  just_audio: ^0.9.36
  syncfusion_flutter_charts: ^33.2.4
  table_calendar:
  google_mobile_ads: ^5.2.0
  firebase_core: ^4.7.0
  cloud_firestore: ^6.3.0
  firebase_auth: ^6.4.0
  firebase_messaging: ^16.2.0
  flutter_local_notifications: ^21.0.0
  permission_handler: ^12.0.1
  flutter_timezone: ^5.1.0
  cloud_functions: ^6.2.0
  share_plus: ^13.1.0
  flutter_email_sender: ^8.0.0
  url_launcher: ^6.3.2
  package_info_plus: ^10.1.0
  in_app_purchase: ^3.2.3
  app_tracking_transparency: ^2.0.6
  firebase_analytics: ^12.4.0
  google_fonts: ^8.1.0
  water_drop_nav_bar: ^2.2.2
  bnb_flutter: ^0.0.4
  curved_labeled_navigation_bar: ^2.0.6
  sleek_circular_slider: ^2.1.0
  build_runner: ^2.15.0
  flutter_gen_runner: ^5.14.1
  http: ^1.6.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  rename: ^3.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/svg/
    - assets/images/png/
    - assets/audio/

  fonts:
    - family: Segoe UI
      fonts:
        - asset: assets/font/Segoe UI.ttf
        - asset: assets/font/Segoe UI Bold.ttf
          weight: 700
        - asset: assets/font/Segoe UI Italic.ttf
          style: italic
        - asset: assets/font/Segoe UI Bold Italic.ttf
          weight: 700
          style: italic
    - family: Lato
      fonts:
        - asset: assets/font/Lato-Regular.ttf
        - asset: assets/font/Lato-Black.ttf
          weight: 900
        - asset: assets/font/Lato-Bold.ttf
          weight: 700
        - asset: assets/font/Lato-Light.ttf
          weight: 300
        - asset: assets/font/Lato-Italic.ttf
          style: italic

flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/wate reminder logo.png"
