// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3t-GZkw14J90irgjMMKIVgrRHD2DOrcw',
    appId: '1:518652564691:android:fcb3abb7df6f2436cd3026',
    messagingSenderId: '518652564691',
    projectId: 'water-reminder-288f9',
    storageBucket: 'water-reminder-288f9.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBRUsQzfdwVP090BvNESppLCm2aiIb8P8',
    appId: '1:518652564691:ios:8fb8038eca609f54cd3026',
    messagingSenderId: '518652564691',
    projectId: 'water-reminder-288f9',
    storageBucket: 'water-reminder-288f9.firebasestorage.app',
    iosBundleId: 'com.water.reminder.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm8qWn2mH9hC57OVB3QP1elcc4JrKpRxE',
    appId: '1:518652564691:web:f034c833acd38727cd3026',
    messagingSenderId: '518652564691',
    projectId: 'water-reminder-288f9',
    authDomain: 'water-reminder-288f9.firebaseapp.com',
    storageBucket: 'water-reminder-288f9.firebasestorage.app',
    measurementId: 'G-XR6Y9ZSY3Y',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBRUsQzfdwVP090BvNESppLCm2aiIb8P8',
    appId: '1:518652564691:ios:8fb8038eca609f54cd3026',
    messagingSenderId: '518652564691',
    projectId: 'water-reminder-288f9',
    storageBucket: 'water-reminder-288f9.firebasestorage.app',
    iosBundleId: 'com.water.reminder.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBm8qWn2mH9hC57OVB3QP1elcc4JrKpRxE',
    appId: '1:518652564691:web:ed9c5939cdee39dbcd3026',
    messagingSenderId: '518652564691',
    projectId: 'water-reminder-288f9',
    authDomain: 'water-reminder-288f9.firebaseapp.com',
    storageBucket: 'water-reminder-288f9.firebasestorage.app',
    measurementId: 'G-72HZYLT3M8',
  );
}
