// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3t-GZkw14J90irgjMMKIVgrRHD2DOrcw',
    appId: '1:518652564691:android:7d60cab557c780adcd3026',
    messagingSenderId: '518652564691',
    projectId: 'water-reminder-288f9',
    storageBucket: 'water-reminder-288f9.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBRUsQzfdwVP090BvNESppLCm2aiIb8P8',
    appId: '1:518652564691:ios:7de6ae325cf6c23ecd3026',
    messagingSenderId: '518652564691',
    projectId: 'water-reminder-288f9',
    storageBucket: 'water-reminder-288f9.firebasestorage.app',
    iosBundleId: 'com.sarang.reminder',
  );
}
